Repository ThePalaceProject/circulation, pull requests merged in 2023-05, with the labels that each got.

#1032 Update configuration for Sirsi Auth
  alembic/versions/20230427_5dcbc92c20b2_update_sirsi_auth_config.py
  api/sirsidynix_authentication_provider.py
  tests/api/test_authenticator.py
  tests/api/test_sirsidynix_auth_provider.py
Labels: DB migration

#1006 Collection based coverage records
  alembic/versions/20230501_f9985f6b7767_remove_import_coverage_records_without_.py
  core/model/coverage.py
  core/opds2_import.py
  core/opds_import.py
  tests/api/test_authenticator.py
  tests/api/test_sirsidynix_auth_provider.py
  tests/core/models/test_collection.py
  tests/core/models/test_coverage.py
  tests/core/test_opds_import.py
Labels: bug, DB migration, incompatible changes

#1082 Remove unnecessary type imports
  api/admin/controller/__init__.py
  api/admin/controller/individual_admin_settings.py
  api/admin/controller/library_settings.py
  api/app.py
  api/authenticator.py
  api/controller.py
  api/saml/configuration/model.py
  api/saml/provider.py
  api/util/flask.py
  core/model/admin.py
  poetry.lock
  pyproject.toml
  tests/api/test_controller_crawlfeed.py
  tests/api/test_controller_opdsfeed.py
  tests/fixtures/api_admin.py
  tests/fixtures/api_controller.py
Labels: dependencies

#1024 Allow Millenium Patron API calls to use POST
  api/millenium_patron.py
  core/model/configuration.py
  tests/api/test_millenium_patron.py
Labels: feature

#1104 ContextManager based advisory locks
  core/model/__init__.py
  tests/core/models/test_model.py
Labels: bug

#1102 Escaping reserved characters in the JSON search type
  core/external_search.py
  tests/core/test_external_search.py
Labels: bug

#1101 Migration to force VLC integrations to use the POST API
  alembic/versions/20230512_5a425ebe026c_migrate_millenium_apis_to_post.py
Labels: DB migration

#1117 Fix Axis360API inheriting from Authenticator
  api/axis.py
Labels: bug

#1127 Test API integrations script
  bin/integration_test
  core/crypt/__init__.py
  core/crypt/aes.py
  core/jobs/integration_test.py
  poetry.lock
  pyproject.toml
  tests/core/jobs/test_integration_test.py
  tests/core/test_crypt_aes.py
Labels: feature
