Repository ThePalaceProject/circulation, pull requests merged in 2023-07, with the labels that each got.

#1227 PP-62 Facets with distributors and collections
  api/controller.py
  api/lanes.py
  api/opds2.py
  core/facets.py
  core/lane.py
  core/model/library.py
  core/opds.py
  core/opds2.py
  scripts.py
  tests/api/test_controller_opdsfeed.py
  tests/api/test_controller_work.py
  tests/api/test_opds2.py
  tests/core/test_external_search.py
  tests/core/test_lane.py
  tests/core/test_opds.py
  tests/core/test_opds2.py
Labels: feature

#1232 PP-134 Search_type and language facets links
  core/lane.py
  tests/core/test_lane.py
  tests/core/test_opds.py
Labels: bug

#1230 Remove unused Adobe vendor ID code 🔥 (PP-135)
  alembic/versions/20230628_f08f9c6bded6_remove_adobe_vendor_id_tables.py
  api/adobe_vendor_id.py
  api/controller.py
  api/routes.py
  bin/configuration/short_client_token_library_configuration
  bin/configuration/vendor_id_library_configuration
  core/model/__init__.py
  core/model/configuration.py
  core/model/credential.py
  core/scripts.py
  core/util/datetime_helpers.py
  pyproject.toml
  tests/api/admin/controller/test_controller.py
  tests/api/admin/test_routes.py
  tests/api/test_adobe_vendor_id.py
  tests/api/test_controller_analytics.py
  tests/api/test_controller_annotation.py
  tests/api/test_controller_cm.py
  tests/api/test_controller_device_manage.py
  tests/api/test_controller_loan.py
  tests/api/test_controller_patron_access_token.py
  tests/api/test_controller_profile.py
  tests/api/test_controller_shared_collect.py
  tests/api/test_controller_work.py
  tests/api/test_enki.py
  tests/api/test_millenium_patron.py
  tests/api/test_odl.py
  tests/api/test_opds.py
  tests/api/test_routes.py
  tests/api/test_scripts.py
  tests/core/models/test_cachedfeed.py
  tests/core/models/test_credential.py
  tests/core/models/test_licensing.py
  tests/core/models/test_work.py
  tests/fixtures/api_controller.py
  tests/fixtures/api_routes.py
  tests/fixtures/vendor_id.py
Labels: DB migration

#1245 Possibly fix the flakiness of core.test_lanes
  tests/core/test_lane.py
Labels: bug

#1259 PP-156 Switched the auto update lists to use sort key pagination
  core/query/customlist.py
  tests/core/test_customlist_queries.py
Labels: bug

#1269 Remove AdobeAuth/devices links from feeds (PP-176)
  api/authenticator.py
  api/opds.py
  tests/api/test_authenticator.py
  tests/api/test_opds.py
Labels: bug

#1277 Update cryptography
  poetry.lock
Labels: dependencies
