Repository ThePalaceProject/circulation, pull requests merged in 2023-11, with the labels that each got.

#1487 PP-495 Analytics as a container service
  README.md
  api/admin/controller/__init__.py
  api/admin/controller/analytics_services.py
  api/admin/controller/base.py
  api/admin/controller/view.py
  api/admin/routes.py
  api/app.py
  api/axis.py
  api/bibliotheca.py
  api/circulation.py
  api/controller.py
  api/discovery/registration_script.py
  api/enki.py
  api/odl.py
  api/overdrive.py
  api/s3_analytics_provider.py
  core/analytics.py
  core/feed/annotator/circulation.py
  core/local_analytics_provider.py
  core/metadata_layer.py
  core/model/licensing.py
  core/service/analytics/configuration.py
  core/service/analytics/container.py
  core/service/configuration.py
  core/service/container.py
  core/util/http.py
  tests/api/admin/controller/test_analytics_services.py
  tests/api/admin/test_routes.py
  tests/api/conftest.py
  tests/api/feed/test_library_annotator.py
  tests/api/mockapi/circulation.py
  tests/api/test_bibliotheca.py
  tests/api/test_controller_analytics.py
  tests/api/test_controller_cm.py
  tests/api/test_controller_loan.py
  tests/api/test_controller_opdsfeed.py
  tests/api/test_overdrive.py
  tests/core/conftest.py
  tests/core/test_analytics.py
  tests/core/test_local_analytics_provider.py
  tests/core/test_metadata.py
  tests/core/test_s3_analytics_provider.py
  tests/fixtures/container.py
  tests/fixtures/database.py
Labels: UI Update, Deployment Changes

#1502 Enforce SIP2 timeout across calls to read on the socket (PP-659)
  api/sip/client.py
  tests/api/sip/test_client.py
Labels: bug

#1509 Fix parameters for enki call (PP-620)
  api/enki.py
  tests/api/mockapi/enki.py
Labels: bug

#1526 Make sure default audience can be selected (PP-752)
  api/saml/configuration/model.py
  core/integration/settings.py
  core/opds_import.py
Labels: bug

#1525 Library short name being saved into library settings (PP-754)
  alembic/versions/20231122_e4b120a8d1d5_remove_short_name_from_library_settings.py
  api/admin/controller/integration_settings.py
  tests/api/admin/controller/test_patron_auth.py
Labels: bug, DB migration

#1498 Remove old columns from collection table
  alembic/versions/20231103_382d7921f500_remove_collection_unused_columns.py
  core/model/collection.py
Labels: DB migration

#1535 Count all eligible licenses (PP-527)
  core/model/licensing.py
  tests/core/models/test_licensing.py
Labels: bug

#1523 Convert MARC Generator to use Integration Configuration (PP-498)
  alembic/versions/20230531_0af587ff8595_migrate_license_integrations_to_.py
  alembic/versions/20230810_0df58829fc1a_add_discovery_service_tables.py
  alembic/versions/20231121_1e46a5bc33b5_migrate_catalog_services.py
  api/admin/controller/catalog_services.py
  api/controller.py
  api/integration/registry/catalog_services.py
  api/marc.py
  core/integration/goals.py
  core/lane.py
  core/marc.py
  core/migration/migrate_external_integration.py
  core/model/cachedfeed.py
  core/model/configuration.py
  core/model/library.py
  pyproject.toml
  scripts.py
  tests/api/admin/controller/test_catalog_services.py
  tests/api/test_controller_marc.py
  tests/api/test_marc.py
  tests/api/test_scripts.py
  tests/core/test_marc.py
  tests/fixtures/database.py
  tests/migration/test_20231121_1e46a5bc33b5.py
Labels: DB migration
