Repository ThePalaceProject/circulation, pull requests merged in 2023-08, with the labels that each got.

#1304 Bump admin UI version (PP-241)
  api/admin/config.py
Labels: dependencies

#1288 Audiobook time tracking
  alembic/versions/20230728_892c8e0c89f8_audiobook_playtime_tracking.py
  api/controller.py
  api/model/time_tracking.py
  api/opds.py
  api/routes.py
  bin/playtime_reporting
  bin/playtime_summation
  core/config.py
  core/jobs/playtime_entries.py
  core/model/__init__.py
  core/model/constants.py
  core/model/time_tracking.py
  core/query/playtime_entries.py
  core/util/datetime_helpers.py
  core/util/email.py
  docker/services/cron/cron.d/circulation
  tests/api/model/test_time_tracking.py
  tests/api/test_controller_playtime_entries.py
  tests/api/test_opds.py
  tests/core/jobs/test_playtime_entries.py
  tests/core/models/test_time_tracking.py
  tests/core/util/test_datetime_helpers.py
Labels: DB migration, feature

#1305 Bump cryptography to 41.0.3
  poetry.lock
Labels: dependencies

#1320 Fix tests that are failing at certain times of the day
  api/admin/controller/dashboard.py
  tests/api/admin/controller/test_dashboard.py
  tests/api/test_circulationapi.py
Labels: bug

#1298 Remove SharedCollectionAPI and IntegrationClient 🔥 (PP-224)
  alembic/versions/20230726_2f1a51aa0ee8_remove_integration_client.py
  api/circulation.py
  api/controller.py
  api/odl.py
  api/odl2.py
  api/opds.py
  api/routes.py
  api/shared_collection.py
  core/metadata_layer.py
  core/model/__init__.py
  core/model/collection.py
  core/model/datasource.py
  core/model/integrationclient.py
  core/model/licensing.py
  core/model/patron.py
  core/opds.py
  tests/api/lcp/test_controller.py
  tests/api/mockapi/circulation.py
  tests/api/test_controller_cm.py
  tests/api/test_controller_crawlfeed.py
  tests/api/test_controller_shared_collect.py
  tests/api/test_odl.py
  tests/api/test_opds.py
  tests/api/test_routes.py
  tests/api/test_shared_collection.py
  tests/core/models/test_collection.py
  tests/core/models/test_integrationclient.py
  tests/core/models/test_patron.py
  tests/fixtures/database.py
  tests/fixtures/odl.py
Labels: DB migration, incompatible changes

#1287 Allow CM to start when running older CM version against new database
  scripts.py
  tests/api/test_scripts.py
Labels: bug

#1336 Correctly handle list and menu collection settings.
  api/admin/controller/collection_settings.py
  api/admin/controller/settings.py
  api/admin/problem_details.py
Labels: bug

#1341 Ensure that lane SQLAlchemy models are properly registered.
  core/lane.py
  core/model/__init__.py
Labels: bug

#1342 Bugfix for OPDS 2 token fulfillment (PP-360)
  api/opds2.py
  core/opds2_import.py
  tests/api/test_opds2.py
  tests/core/test_opds2_import.py
Labels: bug
