Repository ThePalaceProject/circulation, pull requests merged in 2023-10, with the labels that each got.

#1420 Fix missing required argument for update_lane_size script (PP-524)
  core/scripts.py
Labels: bug

#1421 Configure logging integrations via environment variables (PP-496)
  README.md
  api/admin/config.py
  api/admin/controller/__init__.py
  api/admin/controller/sitewide_services.py
  api/admin/routes.py
  api/app.py
  api/controller.py
  api/routes.py
  core/app_server.py
  core/coverage.py
  core/log.py
  core/model/__init__.py
  core/model/configuration.py
  core/monitor.py
  core/scripts.py
  core/service/container.py
  core/service/logging/configuration.py
  core/service/logging/container.py
  core/service/logging/log.py
  core/service/storage/container.py
  poetry.lock
  pyproject.toml
  scripts.py
  tests/api/admin/test_routes.py
  tests/api/test_routes.py
  tests/api/test_scripts.py
  tests/core/service/logging/__init__.py
  tests/core/service/logging/test_configuration.py
  tests/core/service/logging/test_log.py
  tests/core/service/storage/test_s3.py
  tests/core/test_app_server.py
  tests/core/test_log.py
  tests/fixtures/database.py
  tests/fixtures/s3.py
Labels: UI Update, incompatible changes, Deployment Changes

#1379 Remove the externalintegrationslinks table
  alembic/versions/20230913_5d71a80073d5_remove_externalintegrationlink.py
  api/admin/controller/settings.py
  core/model/__init__.py
  core/model/collection.py
  core/model/configuration.py
  tests/core/models/test_configuration.py
  tests/fixtures/database.py
Labels: DB migration

#1458 PP-576 Added the LCP ns to the hashed passphrase
  core/feed/serializer/opds.py
  tests/api/feed/test_opds_serializer.py
Labels: bug

#1464 PP-483 Added last notified date to loan and hold models
  alembic/versions/20231016_21a65b8f391d_loan_and_hold_notification_times.py
  core/jobs/holds_notification.py
  core/model/patron.py
  core/scripts.py
  core/util/notifications.py
  docker/services/cron/cron.d/circulation
  tests/core/test_holds_notifications.py
  tests/core/test_scripts.py
  tests/core/util/test_notifications.py
Labels: DB migration, feature

#1466 Fixed an error while serializing LCP passphrases
  core/feed/serializer/opds2.py
  tests/api/feed/test_opds2_serializer.py
Labels: bug

#1469 PP-598 Removed the google analytics provider
  alembic/versions/20231019_0739d5558dda_cleanup_google_anaytics_integrations.py
  api/admin/controller/analytics_services.py
  api/google_analytics_provider.py
  tests/api/admin/controller/test_analytics_services.py
  tests/api/test_google_analytics_provider.py
  tests/migration/test_20231019_0739d5558dda.py
Labels: DB migration

#1473 Remove odilo integration 🔥 (PP-605)
  api/integration/registry/license_providers.py
  api/odilo.py
  bin/odilo_monitor_recent
  core/model/configuration.py
  core/model/constants.py
  core/model/datasource.py
  docker/services/cron/cron.d/circulation
  tests/api/conftest.py
  tests/api/files/odilo/checkin_ok.json
  tests/api/files/odilo/checkout_acsm_epub_ok.json
  tests/api/files/odilo/checkout_acsm_pdf_ok.json
  tests/api/files/odilo/checkout_ebook_streaming_ok.json
  tests/api/files/odilo/error_checkout_not_found.json
  tests/api/files/odilo/error_data_not_found.json
  tests/api/files/odilo/error_hold_already_in_hold.json
  tests/api/files/odilo/error_hold_not_found.json
  tests/api/files/odilo/error_patron_not_found.json
  tests/api/files/odilo/fulfill_ok_acsm_epub.acsm
  tests/api/files/odilo/fulfill_ok_acsm_pdf.acsm
  tests/api/files/odilo/odilo_availability.json
  tests/api/files/odilo/odilo_availability_inactive.json
  tests/api/files/odilo/odilo_metadata.json
  tests/api/files/odilo/odilo_metadata_inactive.json
  tests/api/files/odilo/patron_checkouts.json
  tests/api/files/odilo/patron_holds.json
  tests/api/files/odilo/place_hold_ok.json
  tests/api/files/odilo/record_availability.json
  tests/api/files/odilo/records_metadata.json
  tests/api/files/odilo/release_hold_ok.json
  tests/api/mockapi/odilo.py
  tests/api/test_monitor.py
  tests/api/test_odilo.py
  tests/fixtures/api_odilo_files.py
Labels: incompatible changes

#1475 PP-139 Switched on OPDS2 capabilities for crawlable feeds
  api/controller.py
Labels: feature

#1474 Add report name to the playtime summary attachment filename.
  core/jobs/playtime_entries.py
  tests/core/jobs/test_playtime_entries.py
Labels: bug

#1476 PP-554 Remove cachedfeeds
  alembic/versions/20231020_7fceb9488bc6_drop_cachedfeeds.py
  api/config.py
  api/controller.py
  api/lanes.py
  bin/cache_opds_blocks
  bin/cache_opds_lane_facets
  bin/database_reaper
  core/config.py
  core/facets.py
  core/feed/annotator/verbose.py
  core/feed/opds.py
  core/lane.py
  core/model/__init__.py
  core/model/cachedfeed.py
  core/model/edition.py
  core/model/library.py
  core/model/work.py
  core/monitor.py
  core/scripts.py
  docker/services/cron/cron.d/circulation
  scripts.py
  tests/api/test_config.py
  tests/api/test_controller_cm.py
  tests/api/test_controller_opdsfeed.py
  tests/api/test_lanes.py
  tests/api/test_scripts.py
  tests/core/models/test_cachedfeed.py
  tests/core/models/test_listeners.py
  tests/core/test_lane.py
  tests/core/test_monitor.py
  tests/core/test_scripts.py
Labels: DB migration

#1477 PP-564 Import duration from palace marketplace
  alembic/versions/20231023_cc084e35e037_add_duration_to_edition.py
  core/feed/annotator/base.py
  core/feed/serializer/opds.py
  core/feed/serializer/opds2.py
  core/feed/types.py
  core/metadata_layer.py
  core/model/edition.py
  core/opds2_import.py
  tests/api/feed/test_annotators.py
  tests/api/feed/test_opds2_serializer.py
  tests/api/feed/test_opds_serializer.py
  tests/core/files/opds2/feed.json
  tests/core/test_metadata.py
  tests/core/test_opds2_import.py
Labels: DB migration, feature
