Repository ThePalaceProject/circulation, pull requests merged in 2023-06, with the labels that each got.

#1180 Move from py-bcrypt to bcrypt library
  core/model/admin.py
  poetry.lock
  pyproject.toml
  tests/core/models/test_admin.py
Labels: dependencies

#577 Bugfix/CM automatically imposed 21 day default loan length to loans without an end
  poetry.lock
  tests/api/test_controller_loan.py
  tests/api/test_opds.py
Labels: bug

#1076 JWE access token implementation
  api/admin/controller/patron_auth_services.py
  api/admin/model/dashboard_statistics.py
  api/authentication/access_token.py
  api/authentication/basic_token.py
  api/authenticator.py
  api/controller.py
  api/integration/registry/patron_auth.py
  api/millenium_patron.py
  api/model/patron_auth.py
  api/problem_details.py
  api/routes.py
  api/sip/__init__.py
  bin/rotate_patron_auth_key
  core/jobs/rotate_jwe_key.py
  core/model/configuration.py
  core/util/authentication_for_opds.py
  core/util/flask_util.py
  docker/services/simplified_crontab
  poetry.lock
  pyproject.toml
  tests/api/admin/controller/test_patron_auth.py
  tests/api/test_authenticator.py
  tests/api/test_basic_token_authentication_provider.py
  tests/api/test_controller_patron_access_token.py
  tests/api/test_jwe_provider.py
  tests/core/jobs/test_rotate_jwe_key.py
  tests/core/util/test_flask_util.py
Labels: dependencies, feature

#1217 PP-68 OPDS2 feeds with relative "next" urls are supported now
  core/opds_import.py
  tests/core/test_opds_import.py
Labels: feature

#1165 Mark OPDS For Distributors titles as explicitly unlimited access
  alembic/versions/20230606_28717fc6e50f_opds_for_distributors_unlimited_access.py
  api/opds_for_distributors.py
  tests/api/test_opds_for_distributors.py
Labels: bug, DB migration

#1215 PP-61 opds2 feed fixes
  api/controller.py
  core/opds2.py
  tests/core/test_opds2.py
Labels: bug
