Repository ThePalaceProject/circulation, pull requests merged in 2023-04, with the labels that each got.

#980 Disable failing patron authentication (DB Migration Required)
  alembic/versions/20230412_dac99ae0c6fd_integration_status.py
  api/authenticator.py
  api/sip/client.py
  bin/update_integration_statuses
  core/jobs/update_integration_status.py
  core/model/__init__.py
  core/model/configuration.py
  core/scripts.py
  docker/services/simplified_crontab
  tests/api/sip/test_client.py
  tests/api/test_authenticator.py
  tests/core/jobs/test_update_integration_status.py
Labels: DB migration, feature

#918 Disallow sign-in redirects to external domains
  api/admin/controller/__init__.py
  tests/api/admin/controller/test_controller.py
Labels: bug

#1018 Moved from elasticsearch-py to opensearch-py
  core/external_search.py
  core/lane.py
  poetry.lock
  pyproject.toml
  tests/core/test_external_search.py
  tests/core/test_lane.py
Labels: dependencies

#1026 Fall back to the patron external_identifier if no username has been s…
  api/opds2.py
Labels: bug

#993 Dashboard stats distinguish unlimited licenses. [requires changes from circulation-admin PR #82]
  api/admin/config.py
  api/admin/controller/__init__.py
  api/admin/dashboard_stats.py
  api/admin/model/__init__.py
  api/admin/model/dashboard_statistics.py
  api/admin/routes.py
  tests/api/admin/test_dashboard_stats.py
  tests/api/admin/test_routes.py
Labels: bug, UI Update, incompatible changes

#1012 Add release notes configuration
  .github/release.yml
Labels: ignore for notes

#1040 Enable the authentication document cache by default
  api/config.py
  api/controller.py
  tests/api/test_controller_cm.py
  tests/api/test_controller_index.py
Labels: bug

#1034 Drop parameterized and use pytest instead.
  poetry.lock
  pyproject.toml
  tests/api/admin/test_validator.py
  tests/api/lcp/test_hash.py
  tests/api/saml/configuration/test_model.py
  tests/api/saml/configuration/test_validator.py
  tests/api/saml/metadata/federations/test_validator.py
  tests/api/saml/metadata/test_filter.py
  tests/api/saml/metadata/test_model.py
  tests/api/saml/metadata/test_parser.py
  tests/core/models/test_configuration.py
  tests/core/models/test_identifier.py
  tests/core/models/test_licensing.py
  tests/core/python_expression_dsl/test_evaluator.py
  tests/core/python_expression_dsl/test_parser.py
  tests/core/test_external_search.py
  tests/core/test_metadata.py
  tests/core/util/test_datetime_helpers.py
  tests/core/util/test_flask_util.py
  tests/core/util/test_opds_writer.py
Labels: dependencies

#1033 Make sure remote_patron_lookup calls are necessary
  api/authenticator.py
  tests/api/test_authenticator.py
Labels: bug
