Repository ThePalaceProject/circulation, pull requests merged in 2023-12, with the labels that each got.

#1553 Hold notifiations now include a short title and a body with details (PP-753)
  core/util/notifications.py
  tests/core/util/test_notifications.py
Labels: bug

#1547 MARC export by collection (PP-59)
  alembic/versions/20231128_0039f3f12014_marc_export_by_collection.py
  api/admin/controller/collection_settings.py
  api/admin/controller/work_editor.py
  api/axis.py
  api/bibliotheca.py
  api/circulation.py
  api/controller.py
  api/controller_marc.py
  api/enki.py
  api/marc.py
  api/overdrive.py
  bin/marc_record_coverage
  core/coverage.py
  core/lane.py
  core/marc.py
  core/model/__init__.py
  core/model/cachedfeed.py
  core/model/collection.py
  core/model/coverage.py
  core/model/library.py
  core/model/marcfile.py
  core/model/resource.py
  core/model/work.py
  core/opds_import.py
  core/scripts.py
  core/service/storage/s3.py
  core/util/uuid.py
  docker/services/cron/cron.d/circulation
  pyproject.toml
  scripts.py
  tests/api/test_controller_marc.py
  tests/api/test_marc.py
  tests/api/test_scripts.py
  tests/core/models/test_marcfile.py
  tests/core/models/test_work.py
  tests/core/service/storage/test_s3.py
  tests/core/test_coverage.py
  tests/core/test_marc.py
  tests/core/test_opds_import.py
  tests/core/test_scripts.py
  tests/core/util/test_uuid.py
  tests/fixtures/s3.py
  tests/migration/test_20231124_1c14468b74ce.py
Labels: DB migration, feature

#1552 MARC export by collection - Cleanup Migration (PP-59)
  alembic/versions/20231204_d3cdbea3d43b_marc_export_cleanup_migration.py
  alembic/versions/20231206_e06f965879ab_marc_s3_file_cleanup.py
  core/model/__init__.py
  core/model/cachedfeed.py
  core/model/work.py
  core/service/storage/s3.py
  tests/core/service/storage/test_s3.py
  tests/migration/conftest.py
  tests/migration/test_20231206_e06f965879ab.py
Labels: DB migration, cleanup migration

#1560 Fix 2d72d6876c52 migration failure with overdrive advantage collections
  alembic/versions/20231101_2d72d6876c52_remove_collection_external_integration.py
  tests/migration/test_20231101_2d72d6876c52.py
Labels: bug, DB migration

#1549 Add per-medium breakouts to dashboard statistics inventories. (PP-728)
  api/admin/config.py
  api/admin/dashboard_stats.py
  api/admin/model/dashboard_statistics.py
  pyproject.toml
  tests/api/admin/test_dashboard_stats.py
Labels: UI Update, feature, incompatible changes

#1568 Handle `null` medium in dashboard stats. (PP-728)
  api/admin/dashboard_stats.py
  tests/api/admin/test_dashboard_stats.py
Labels: bug

#1571 Fix flaky marc test
  tests/core/test_marc.py
Labels: bug
