Repository ThePalaceProject/circulation, pull requests merged in 2024-04, with the labels that each got.

#1763 Fix interpolation issue with JSONFormatter
  core/service/logging/log.py
  tests/core/service/logging/test_log.py
Labels: bug

#1781 Update quicksight configuration (PP-1154)
  README.md
  api/admin/controller/__init__.py
  api/admin/controller/quicksight.py
  core/config.py
  core/service/configuration.py
  core/service/sitewide.py
  tests/api/admin/controller/test_quicksight.py
  tests/core/service/test_sitewide.py
Labels: incompatible changes

#1782 Update fcm to use service container (PP-1154)
  README.md
  core/config.py
  core/jobs/holds_notification.py
  core/jobs/patron_activity_sync.py
  core/scripts.py
  core/service/container.py
  core/service/fcm/__init__.py
  core/service/fcm/configuration.py
  core/service/fcm/container.py
  core/service/fcm/fcm.py
  core/util/notifications.py
  tests/api/test_config.py
  tests/core/files/service/fcm/fcm-credentials-valid-json.json
  tests/core/files/service/fcm/not-valid-json.txt
  tests/core/service/fcm/__init__.py
  tests/core/service/fcm/test_fcm.py
  tests/core/test_holds_notifications.py
  tests/core/test_patron_activity_sync.py
  tests/core/test_scripts.py
Labels: incompatible changes

#1787 Fix celery log folder creation (PP-1142)
  core/celery/tasks/custom_list.py
  docker/Dockerfile
  docker/runit-scripts/beat/run
  docker/runit-scripts/worker-default/run
  docker/runit-scripts/worker-high/run
Labels: bug

#1793 Fix thread safety issue in patron_activity (PP-1155)
  api/circulation.py
  tests/api/test_bibliotheca.py
  tests/api/test_circulationapi.py
  tests/api/test_overdrive.py
Labels: bug

#1799 Update to xmlsec v1.3.14
  .github/workflows/codeql-analysis.yml
  .github/workflows/mypy.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  docker/Dockerfile
  docker/Dockerfile.baseimage
  poetry.lock
  poetry.toml
Labels: dependencies, python

#1794 [PP-1157] convert inventory and hold reports to celery
  api/admin/controller/report.py
  bin/delete_old_deferred_tasks
  bin/generate_inventory_reports
  core/celery/job.py
  core/celery/tasks/generate_inventory_and_hold_reports.py
  core/scripts.py
  docker/services/cron/cron.d/circulation
  tests/api/admin/controller/test_report.py
  tests/core/celery/tasks/test_generate_inventory_and_hold_reports.py
  tests/core/test_scripts.py
Labels: cleanup migration

#1795 [PP-1158] Remove deferredtasks.
  alembic/versions/20240417_f532186a3d48_remove_deferredtasks_table.py
  core/model/__init__.py
  core/model/deferredtask.py
  tests/core/models/test_deferredtask.py
Labels: DB migration

#1808 Fix unreleated unresolved symbols (PP-1161)
  bin/custom_list_entry_update_license_pool
  src/palace/manager/core/classifier/__init__.py
  src/palace/manager/core/metadata_layer.py
  src/palace/manager/util/personal_names.py
  tests/manager/api/admin/dummy_validator/__init__.py
  tests/manager/api/admin/dummy_validator/dummy_validator.py
  tests/manager/api/admin/dummy_validator/dummy_validator_factory.py
  tests/manager/api/admin/test_validator.py
  tests/manager/core/test_metadata.py
Labels: bug
