Repository ThePalaceProject/circulation, pull requests merged in 2024-09, with the labels that each got.

#2024 Add better bibliotheca error messages (PP-1637)
  src/palace/manager/api/bibliotheca.py
  src/palace/manager/api/circulation_exceptions.py
  tests/manager/api/test_bibliotheca.py
Labels: bug

#2002 [PP-1456] Add loan count column to audio book playback time reports.
  alembic/versions/20240821_7a2fcaac8b63_add_loan_identifier_column_to_playtime_tables.py
  src/palace/manager/api/controller/playtime_entries.py
  src/palace/manager/core/query/playtime_entries.py
  src/palace/manager/scripts/playtime_entries.py
  src/palace/manager/sqlalchemy/model/time_tracking.py
  tests/manager/api/controller/test_playtime_entries.py
  tests/manager/scripts/test_playtime_entries.py
  tests/manager/sqlalchemy/model/test_time_tracking.py
Labels: feature

#2019 Add a script to clean up old marc file exports (PP-348)
  src/palace/manager/celery/tasks/marc.py
  src/palace/manager/marc/exporter.py
  src/palace/manager/service/celery/celery.py
  src/palace/manager/sqlalchemy/model/marcfile.py
  tests/fixtures/marc.py
  tests/fixtures/s3.py
  tests/manager/celery/tasks/test_marc.py
  tests/manager/marc/test_exporter.py
  tests/manager/service/storage/test_s3.py
Labels: feature

#2028 Fix bug with playtime migration with existing data
  alembic/versions/20240821_7a2fcaac8b63_add_loan_identifier_column_to_playtime_tables.py
Labels: bug

#2029 Fix non-canonical protocol not showing settings (PP-1472)
  src/palace/manager/api/admin/controller/integration_settings.py
  src/palace/manager/service/integration_registry/base.py
  tests/manager/api/admin/controller/test_integration_settings.py
  tests/manager/service/integration_registry/test_base.py
Labels: bug

#2033 Return problem detail when LCP fulfillment fails (PP-1641)
  src/palace/manager/api/odl/api.py
  tests/manager/api/odl/test_api.py
Labels: bug

#2036 Update Enki non-DRM to use RedirectFulfillment
  src/palace/manager/api/enki.py
  tests/manager/api/test_enki.py
Labels: bug

#2048 Add user agent to logs
  src/palace/manager/service/logging/log.py
  tests/manager/service/logging/test_log.py
Labels: feature

#2045 Fix issues caused by differences between redis and elasticache (PP-1693)
  src/palace/manager/celery/tasks/marc.py
  src/palace/manager/service/redis/escape.py
  src/palace/manager/service/redis/models/lock.py
  src/palace/manager/service/redis/models/marc.py
  src/palace/manager/service/redis/redis.py
  tests/manager/service/redis/models/test_marc.py
  tests/manager/service/redis/test_escape.py
Labels: bug

#2050 Ensures that the overdrive new titles script does not fail when cover…
  src/palace/manager/core/coverage.py
  tests/manager/core/test_coverage.py
  tests/mocks/mock.py
Labels: bug

#2053 Fix another S3 multipart upload issue with marc exporter (PP-1693)
  src/palace/manager/marc/uploader.py
  src/palace/manager/service/redis/models/marc.py
  tests/fixtures/s3.py
  tests/manager/marc/test_uploader.py
  tests/manager/service/redis/models/test_marc.py
Labels: bug

#2055 Don't proxy the full response headers (PP-1713)
  src/palace/manager/api/circulation.py
  tests/manager/api/test_circulation.py
Labels: bug

#2030 Migrate MARC exporter protocol name
  alembic/versions/20240905_350a29bf0ff0_update_existing_marcexporter_protocols.py
  src/palace/manager/service/integration_registry/catalog_services.py
Labels: DB migration

#2057 OPDS2 + ODL Handle case where no licenses are available (PP-1716)
  src/palace/manager/api/odl/api.py
  tests/files/odl/unavailable.json
  tests/manager/api/odl/test_api.py
Labels: bug

#2060 Don't cache overdrive token in credentials table (PP-1717)
  src/palace/manager/api/overdrive.py
  tests/manager/api/test_overdrive.py
Labels: bug, cleanup migration

#2049 Allow restriction to multiple patron locations. (PP-1648)
  src/palace/manager/api/authentication/base.py
  src/palace/manager/api/authentication/basic.py
  src/palace/manager/api/sip/__init__.py
  tests/manager/api/sip/test_authentication_provider.py
  tests/manager/api/test_authenticator.py
  tests/manager/api/test_sirsidynix_auth_provider.py
Labels: feature

#2074 Fix uncommitted nested transaction in SweepMonitor (PP-1717)
  src/palace/manager/api/axis.py
  src/palace/manager/api/overdrive.py
  src/palace/manager/core/monitor.py
Labels: bug

#2077 Fix uwsgi log file permissions (PP-1667)
  docker/Dockerfile
  docker/services/logrotate/logrotate.d/celery.conf
  docker/services/logrotate/logrotate.d/simplified.conf
  docker/services/uwsgi/uwsgi.d/40_log.ini
Labels: bug

#2083 fix: opds2-reaper-monitor-script (PP-1756)
  bin/opds2_reaper_monitor
Labels: bug

#2085 Update license pools for ODL licenses that are loan + concurrency limited
  src/palace/manager/sqlalchemy/model/licensing.py
  tests/manager/api/odl/test_importer.py
  tests/manager/sqlalchemy/model/test_licensing.py
Labels: bug
