Repository ThePalaceProject/circulation, pull requests merged in 2024-06, with the labels that each got.

#1885 Fix ODL License status document checks (PP-1331)
  src/palace/manager/api/odl.py
  tests/manager/api/test_odl.py
Labels: bug

#1872 [PP-978] Add work suppression for library api calls.
  src/palace/manager/api/admin/controller/work_editor.py
  src/palace/manager/api/admin/routes.py
  tests/manager/api/admin/controller/test_work_editor.py
  tests/manager/api/admin/test_routes.py
Labels: feature

#1886 Ensures that fiction metadata element is being stored in the search i…
  src/palace/manager/sqlalchemy/model/work.py
  tests/manager/celery/tasks/test_search.py
  tests/manager/sqlalchemy/model/test_work.py
Labels: bug

#1888 ODL2 collections can disallow holds at the collection level. (PP-1316)
  src/palace/manager/api/circulation_exceptions.py
  src/palace/manager/api/odl2.py
  src/palace/manager/api/problem_details.py
  src/palace/manager/sqlalchemy/model/lane.py
  tests/manager/api/admin/test_validator.py
  tests/manager/api/controller/test_loan.py
  tests/manager/api/test_odl2.py
  tests/manager/sqlalchemy/model/test_lane.py
Labels: feature

#1899 Add a refresh query parameter to the loans feed (PP-1368)
  src/palace/manager/api/controller/loan.py
  tests/manager/api/controller/test_loan.py
Labels: feature

#1894 Remote patron activity sync celery task (PP-1164)
  README.md
  docker-compose.yml
  poetry.lock
  pyproject.toml
  src/palace/manager/api/circulation.py
  src/palace/manager/api/circulation_manager.py
  src/palace/manager/api/controller/circulation_manager.py
  src/palace/manager/api/controller/loan.py
  src/palace/manager/api/opds_for_distributors.py
  src/palace/manager/celery/tasks/patron_activity.py
  src/palace/manager/service/container.py
  src/palace/manager/service/integration_registry/license_providers.py
  src/palace/manager/service/redis/__init__.py
  src/palace/manager/service/redis/configuration.py
  src/palace/manager/service/redis/container.py
  src/palace/manager/service/redis/exception.py
  src/palace/manager/service/redis/key.py
  src/palace/manager/service/redis/models/__init__.py
  src/palace/manager/service/redis/models/patron_activity.py
  src/palace/manager/service/redis/redis.py
  src/palace/manager/sqlalchemy/model/collection.py
  src/palace/manager/sqlalchemy/model/licensing.py
  src/palace/manager/sqlalchemy/model/patron.py
  src/palace/manager/util/datetime_helpers.py
  tests/conftest.py
  tests/fixtures/database.py
  tests/fixtures/redis.py
  tests/manager/api/controller/test_base.py
  tests/manager/api/controller/test_loan.py
  tests/manager/api/test_bibliotheca.py
  tests/manager/api/test_circulationapi.py
  tests/manager/api/test_opds_for_distributors.py
  tests/manager/api/test_overdrive.py
  tests/manager/celery/tasks/test_patron_activity.py
  tests/manager/feed/test_library_annotator.py
  tests/manager/service/redis/__init__.py
  tests/manager/service/redis/models/__init__.py
  tests/manager/service/redis/models/test_patron_activity.py
  tests/manager/service/redis/test_key.py
  tests/manager/service/redis/test_redis.py
  tests/manager/sqlalchemy/model/test_collection.py
  tests/manager/sqlalchemy/model/test_licensing.py
  tests/manager/sqlalchemy/model/test_patron.py
  tests/mocks/circulation.py
  tox.ini
Labels: cleanup migration, feature, incompatible changes

#1905 Per-library work suppression is idempotent. (PP-1378)
  src/palace/manager/api/admin/controller/work_editor.py
  tests/manager/api/admin/controller/test_work_editor.py
Labels: bug

#1904 Celery logging config
  src/palace/manager/celery/app.py
  tests/manager/celery/tasks/test_search.py
  tests/manager/celery/test_monitoring.py
Labels: bug

#1903 ODL availability proposal (PP-869)
  bin/opds2_import_monitor
  poetry.lock
  pyproject.toml
  src/palace/manager/api/odl2.py
  src/palace/manager/core/opds2_import.py
  tests/files/odl2/feed.json
  tests/manager/api/test_odl2.py
  tests/manager/core/test_opds2_import.py
Labels: feature

#1897 Remove patron.last_loan_activity_sync
  alembic/versions/20240612_7ba553f3f80d_remove_patron_last_loan_activity_sync.py
  src/palace/manager/sqlalchemy/model/patron.py
Labels: DB migration

#1909 Update indexing task to use bulk indexing endpoint (PP-1382)
  src/palace/manager/celery/tasks/search.py
  src/palace/manager/service/celery/celery.py
  src/palace/manager/service/redis/models/lock.py
  src/palace/manager/service/redis/models/search.py
  src/palace/manager/service/redis/redis.py
  src/palace/manager/sqlalchemy/listeners.py
  src/palace/manager/sqlalchemy/model/work.py
  tests/fixtures/database.py
  tests/fixtures/search.py
  tests/manager/celery/tasks/test_search.py
  tests/manager/service/redis/models/test_lock.py
  tests/manager/service/redis/models/test_search.py
  tests/manager/sqlalchemy/model/test_customlist.py
  tests/manager/sqlalchemy/model/test_work.py
  tests/manager/sqlalchemy/test_listeners.py
Labels: bug

#1912 Overdrive API patron_activity returning None
  src/palace/manager/api/overdrive.py
  tests/manager/api/test_overdrive.py
Labels: bug

#1914 Add support for SQS to our Celery configuration (PP-1397)
  poetry.lock
  pyproject.toml
  src/palace/manager/service/celery/configuration.py
  tests/manager/service/celery/test_configuration.py
Labels: feature

#1920 Fix bug with OPDS2 schema validation (PP-1414)
  poetry.lock
  pyproject.toml
  src/palace/manager/core/opds_schema.py
  src/palace/manager/resources/opds2_schema/cached/drafts.opds.io/schema_acquisition-object.schema.json
  src/palace/manager/resources/opds2_schema/cached/drafts.opds.io/schema_feed-metadata.schema.json
  src/palace/manager/resources/opds2_schema/cached/drafts.opds.io/schema_feed.schema.json
  src/palace/manager/resources/opds2_schema/cached/drafts.opds.io/schema_properties.schema.json
  src/palace/manager/resources/opds2_schema/cached/drafts.opds.io/schema_publication.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_contributor-object.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_contributor.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_experimental_presentation_metadata.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_experimental_presentation_properties.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_extensions_divina_properties.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_extensions_encryption_properties.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_extensions_epub_metadata.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_extensions_epub_properties.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_language-map.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_link.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_metadata.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_subject-object.schema.json
  src/palace/manager/resources/opds2_schema/cached/readium.org/webpub-manifest_schema_subject.schema.json
  src/palace/manager/resources/opds2_schema/odl-feed.schema.json
  src/palace/manager/resources/opds2_schema/odl-licenses.schema.json
  src/palace/manager/resources/opds2_schema/odl-publication.schema.json
  src/palace/manager/resources/opds2_schema/readium-metadata.schema.json
  tests/files/odl2/feed2.json
  tests/files/opds2/bad_feed.json
  tests/files/opds2/bad_feed2.json
  tests/files/opds2/feed2.json
  tests/fixtures/api_odl.py
  tests/fixtures/files.py
  tests/fixtures/odl.py
  tests/manager/api/test_odl2.py
  tests/manager/core/test_opds2_import.py
  tests/manager/core/test_opds_validate.py
Labels: bug
