Repository ThePalaceProject/circulation, pull requests merged in 2024-02, with the labels that each got.

#1664 Add a new key table to hold some of our sitewide keys (PP-893)
  alembic/versions/20240207_fc3c9ccf0ad8_add_keys_table.py
  api/admin/password_admin_authentication_provider.py
  api/app.py
  api/authentication/access_token.py
  api/authentication/basic_token.py
  api/authenticator.py
  api/controller/patron_auth_token.py
  core/jobs/rotate_jwe_key.py
  core/model/__init__.py
  core/model/key.py
  core/util/string_helpers.py
  core/util/uuid.py
  pyproject.toml
  scripts.py
  tests/api/authentication/__init__.py
  tests/api/authentication/test_access_token.py
  tests/api/authentication/test_basic_token.py
  tests/api/test_authenticator.py
  tests/api/test_jwe_provider.py
  tests/core/jobs/test_rotate_jwe_key.py
  tests/core/models/test_key.py
  tests/core/util/test_string_helpers.py
  tests/core/util/test_uuid.py
  tests/fixtures/api_admin.py
  tests/fixtures/database.py
Labels: DB migration

#1648 Move sitewide settings to environment variables (PP-494)
  README.md
  api/admin/config.py
  api/admin/controller/__init__.py
  api/admin/controller/base.py
  api/admin/controller/settings.py
  api/admin/controller/sitewide_settings.py
  api/admin/controller/view.py
  api/admin/routes.py
  api/app.py
  api/authenticator.py
  api/circulation_manager.py
  api/config.py
  api/discovery/registration_script.py
  bin/configuration/configure_site_setting
  core/config.py
  core/external_search.py
  core/jobs/holds_notification.py
  core/jobs/patron_activity_sync.py
  core/model/collection.py
  core/model/configuration.py
  core/monitor.py
  core/scripts.py
  core/service/container.py
  core/service/sitewide.py
  core/util/notifications.py
  docker-compose.yml
  docker/startup/01_set_simplified_environment.sh
  scripts.py
  tests/api/admin/controller/test_settings.py
  tests/api/admin/controller/test_sitewide_settings.py
  tests/api/admin/controller/test_view.py
  tests/api/admin/test_routes.py
  tests/api/controller/test_analytics.py
  tests/api/controller/test_annotation.py
  tests/api/controller/test_base.py
  tests/api/controller/test_loan.py
  tests/api/controller/test_patron_access_token.py
  tests/api/controller/test_profile.py
  tests/api/controller/test_scopedsession.py
  tests/api/controller/test_work.py
  tests/api/discovery/test_opds_registration.py
  tests/api/test_authenticator.py
  tests/api/test_controller_cm.py
  tests/api/test_scripts.py
  tests/core/models/test_collection.py
  tests/core/models/test_configuration.py
  tests/core/service/test_sitewide.py
  tests/core/test_external_search.py
  tests/core/test_holds_notifications.py
  tests/core/test_monitor.py
  tests/core/test_patron_activity_sync.py
  tests/core/test_scripts.py
  tests/core/util/test_notifications.py
  tests/fixtures/api_admin.py
  tests/fixtures/api_controller.py
  tests/fixtures/api_routes.py
  tests/fixtures/services.py
Labels: UI Update, Deployment Changes

#1677 Make sure expired tokens give correct status / problem detail (PP-970)
  api/authentication/access_token.py
  api/authentication/basic_token.py
  api/authenticator.py
  tests/api/authentication/test_access_token.py
  tests/api/authentication/test_basic_token.py
  tests/api/test_authenticator.py
Labels: bug

#1680 Suppress works on a per library basis (PP-939)
  alembic/versions/20240216_9d2dccb0d6ff_ability_to_suppress_works_per_library.py
  bin/configuration/suppress_work_for_library
  core/external_search.py
  core/lane.py
  core/model/listeners.py
  core/model/work.py
  core/scripts.py
  tests/core/models/test_listeners.py
  tests/core/models/test_work.py
  tests/core/test_external_search.py
  tests/core/test_lane.py
  tests/core/test_scripts.py
Labels: DB migration, feature

#1688 Fixes lane saving bug
  api/admin/controller/custom_lists.py
  api/admin/controller/lanes.py
  core/lane.py
Labels: bug

#1694 Refactor circulation exceptions (PP-991)
  api/admin/exceptions.py
  api/admin/routes.py
  api/axis.py
  api/bibliotheca.py
  api/circulation.py
  api/circulation_exceptions.py
  api/controller/base.py
  api/controller/loan.py
  api/enki.py
  api/odl.py
  api/overdrive.py
  api/problem_details.py
  api/util/patron.py
  core/app_server.py
  core/exceptions.py
  core/opds2_import.py
  core/opds_import.py
  core/user_profile.py
  core/util/http.py
  core/util/problem_detail.py
  pyproject.toml
  tests/api/controller/test_loan.py
  tests/api/metadata/test_nyt.py
  tests/api/test_axis.py
  tests/api/test_bibliotheca.py
  tests/api/test_circulation_exceptions.py
  tests/api/test_circulationapi.py
  tests/api/test_enki.py
  tests/api/test_opds_for_distributors.py
  tests/api/test_overdrive.py
  tests/api/test_patron_utility.py
  tests/core/test_app_server.py
  tests/core/util/test_http.py
Labels: bug

#1698 Fix AttributeError causing Loan Notification script to fail (PP-997)
  core/util/notifications.py
  tests/core/util/test_notifications.py
Labels: bug

#1699 Fix circular import issue. (PP-1016)
  api/saml/metadata/federations/loader.py
  api/saml/metadata/federations/validator.py
  bin/configuration/add_saml_federations.py
Labels: bug

#1700 Raise RemoteInitiatedServerError on expired session key (PP-996)
  api/axis.py
  api/controller/loan.py
  tests/api/test_axis.py
Labels: bug
