Repository ThePalaceProject/circulation, pull requests merged in 2024-12, with the labels that each got.

#2182 [PP-1914] Remove collection facet from feed.
  src/palace/manager/api/lanes.py
  src/palace/manager/core/facets.py
  src/palace/manager/integration/configuration/library.py
  src/palace/manager/search/external_search.py
  src/palace/manager/sqlalchemy/model/lane.py
  tests/manager/api/controller/test_work.py
  tests/manager/api/test_lanes.py
  tests/manager/feed/test_library_annotator.py
  tests/manager/feed/test_opds_acquisition_feed.py
  tests/manager/search/test_external_search.py
  tests/manager/sqlalchemy/model/test_lane.py
  tests/manager/sqlalchemy/model/test_library.py
Labels: cleanup migration

#2199 Make sure we handle ProblemDetail response from _crawlable_feed (PP-1975)
  src/palace/manager/api/controller/opds_feed.py
  tests/manager/api/controller/test_crawlfeed.py
Labels: bug

#2198 Filter work summary to remove non-xml safe characters (PP-1969)
  alembic/versions/20241127_c3458e1ef9aa_remove_unsafe_characters_summary.py
  src/palace/manager/sqlalchemy/model/work.py
  tests/manager/sqlalchemy/model/test_edition.py
Labels: bug, DB migration

#2207 Retry celery patron sync on StaleDataError (PP-2005)
  src/palace/manager/celery/tasks/patron_activity.py
  tests/manager/celery/tasks/test_patron_activity.py
Labels: bug

#2174 [PP-1358] add new events
  src/palace/manager/api/circulation.py
  src/palace/manager/api/monitor.py
  src/palace/manager/celery/tasks/opds_odl.py
  src/palace/manager/core/monitor.py
  src/palace/manager/sqlalchemy/model/circulationevent.py
  tests/manager/api/test_authenticator.py
  tests/manager/api/test_circulationapi.py
  tests/manager/api/test_monitor.py
  tests/manager/celery/tasks/test_opds_odl.py
  tests/mocks/analytics_provider.py
Labels: DB migration, feature

#2204 Add migration to remove obsolete settings (facets_enabled_collection …
  alembic/versions/20241202_603b8ebd6daf_remove_collection_facet_settings.py
Labels: DB migration

#2216 Fix format sweep script by ensuring all operations within the context…
  src/palace/manager/api/circulation.py
  src/palace/manager/core/metadata_layer.py
  src/palace/manager/sqlalchemy/model/licensing.py
Labels: bug
