Repository ThePalaceProject/circulation, pull requests merged in 2024-08, with the labels that each got.

#1969 [PP-1544] Do not specify target age on interest level classifier for …
  src/palace/manager/core/classifier/age.py
  tests/manager/core/classifiers/test_age.py
Labels: bug

#1966 [PP-1525] Add support for bypassing user blocks on Sirsidynix Authent…
  src/palace/manager/api/sirsidynix_authentication_provider.py
  tests/manager/api/test_sirsidynix_auth_provider.py
Labels: feature

#1982 Fix bug in HTTP._request_with_timeout when headers are None (PP-1582)
  src/palace/manager/util/http.py
  tests/manager/util/test_http.py
Labels: bug

#1981 [PP-1556] Fix broken time tracking summary script.
  src/palace/manager/sqlalchemy/model/time_tracking.py
  tests/manager/sqlalchemy/model/test_time_tracking.py
Labels: bug

#1983 Fix admin UI setting for Library Identifier Field
  src/palace/manager/api/authentication/basic.py
Labels: bug

#1996 Add freeze_time decorator to test_compressible
  tests/manager/core/test_app_server.py
Labels: bug

#2008 Prune old migrations
  alembic/versions/20231019_0739d5558dda_cleanup_google_anaytics_integrations.py
  alembic/versions/20231020_7fceb9488bc6_drop_cachedfeeds.py
  alembic/versions/20231023_cc084e35e037_add_duration_to_edition.py
  alembic/versions/20231101_2d72d6876c52_remove_collection_external_integration.py
  alembic/versions/20231103_382d7921f500_remove_collection_unused_columns.py
  alembic/versions/20231121_1e46a5bc33b5_migrate_catalog_services.py
  alembic/versions/20231122_e4b120a8d1d5_remove_short_name_from_library_settings.py
  alembic/versions/20231124_1c14468b74ce_biblioboard_licensepools_time_tracking_.py
  alembic/versions/20231124_6af9160a578e_licensepools_time_tracking_flag.py
  alembic/versions/20231128_0039f3f12014_marc_export_by_collection.py
  alembic/versions/20231204_d3cdbea3d43b_marc_export_cleanup_migration.py
  alembic/versions/20231206_e06f965879ab_marc_s3_file_cleanup.py
  alembic/versions/20240104_735bf6ced8b9_update_license_provider_settings.py
  alembic/versions/20240124_993729d4bf97_migrate_metadata_services.py
  alembic/versions/20240207_fc3c9ccf0ad8_add_keys_table.py
  alembic/versions/20240208_1c9f519415b5_remove_external_integration.py
  alembic/versions/20240216_9d2dccb0d6ff_ability_to_suppress_works_per_library.py
  docker/ci/test_migrations.yml
  src/palace/manager/util/migration/migrate_external_integration.py
  tests/migration/conftest.py
  tests/migration/test_20231019_0739d5558dda.py
  tests/migration/test_20231101_2d72d6876c52.py
  tests/migration/test_20231121_1e46a5bc33b5.py
  tests/migration/test_20231124_1c14468b74ce.py
  tests/migration/test_20231206_e06f965879ab.py
Labels: incompatible changes
