Repository ThePalaceProject/circulation, pull requests merged in 2024-05, with the labels that each got.

#1836 Search index rebuild script undefined variable
  src/palace/manager/core/scripts.py
Labels: bug

#1849 Update search indexing to use celery rather then coverage records (PP-1225)
  bin/search_index_clear
  bin/search_index_refresh
  docker/services/cron/cron.d/circulation
  pyproject.toml
  src/palace/manager/api/admin/controller/custom_lists.py
  src/palace/manager/celery/tasks/search.py
  src/palace/manager/scripts/initialization.py
  src/palace/manager/scripts/search.py
  src/palace/manager/search/coverage_provider.py
  src/palace/manager/search/coverage_remover.py
  src/palace/manager/search/external_search.py
  src/palace/manager/search/migrator.py
  src/palace/manager/search/revision.py
  src/palace/manager/search/revision_directory.py
  src/palace/manager/search/service.py
  src/palace/manager/search/v5.py
  src/palace/manager/service/celery/celery.py
  src/palace/manager/service/search/container.py
  src/palace/manager/sqlalchemy/model/work.py
  src/palace/manager/util/backoff.py
  tests/fixtures/api_controller.py
  tests/fixtures/database.py
  tests/fixtures/search.py
  tests/fixtures/services.py
  tests/manager/celery/tasks/test_search.py
  tests/manager/scripts/test_informational.py
  tests/manager/scripts/test_initialization.py
  tests/manager/scripts/test_lane.py
  tests/manager/scripts/test_search.py
  tests/manager/search/test_external_search.py
  tests/manager/search/test_migration_states.py
  tests/manager/search/test_migrator.py
  tests/manager/search/test_search_revision_directory.py
  tests/manager/search/test_service.py
  tests/manager/sqlalchemy/model/test_customlist.py
  tests/manager/sqlalchemy/model/test_lane.py
  tests/manager/sqlalchemy/model/test_work.py
  tests/manager/sqlalchemy/test_listeners.py
  tests/manager/util/test_backoff.py
  tests/migration/test_instance_init_script.py
  tests/mocks/search.py
Labels: cleanup migration, feature

#1860 Admin must have role for a library to generate inventory report. (PP-1293)
  src/palace/manager/api/admin/controller/report.py
  src/palace/manager/api/admin/routes.py
  tests/manager/api/admin/controller/test_report.py
Labels: bug

#1861 Remove old update-search-index work coverage records (PP-1279)
  alembic/versions/20240522_50746a3bd243_remove_update_search_index_work_.py
  src/palace/manager/sqlalchemy/model/coverage.py
Labels: DB migration

#1871 Fix issue with monitoring queue stats (PP-1312)
  src/palace/manager/celery/monitoring.py
  tests/manager/celery/test_monitoring.py
Labels: bug

#1878 Fix run script path for custom list update script
  docker/services/cron/cron.d/circulation
Labels: bug
