Repository ThePalaceProject/circulation, pull requests merged in 2024-03, with the labels that each got.

#1715 Initialize CachedData cache for `distributor` customlist searches. (PP-1045)
  bin/custom_list_update_new_entries
Labels: bug

#1714 Bugfix for hold notifications happening for expired holds (PP-1048)
  core/jobs/holds_notification.py
  core/util/notifications.py
  tests/core/test_holds_notifications.py
  tests/core/util/test_notifications.py
Labels: bug

#1729 Update concurrency groups
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ignore for notes

#1739 Playback time tables are independent of related tables. (PP-1044)
  alembic/versions/20240318_3e43ed59f256_playtime_tables_have_no_dependencies.py
  core/jobs/playtime_entries.py
  core/model/identifier.py
  core/model/time_tracking.py
  core/query/playtime_entries.py
  core/util/datetime_helpers.py
  tests/api/controller/test_playtime_entries.py
  tests/core/jobs/test_playtime_entries.py
  tests/core/models/test_time_tracking.py
  tests/core/util/test_datetime_helpers.py
Labels: bug, DB migration

#1734 Feature/pp 1027 implement backend report functionality
  alembic/versions/20240319_b2353c25a95e_add_deferredtasks_table.py
  api/admin/controller/__init__.py
  api/admin/controller/report.py
  api/admin/routes.py
  api/circulation_manager.py
  bin/delete_old_deferred_tasks
  bin/generate_inventory_reports
  core/model/__init__.py
  core/model/deferredtask.py
  core/opds_import.py
  core/scripts.py
  docker/services/cron/cron.d/circulation
  pyproject.toml
  tests/api/admin/controller/test_report.py
  tests/core/models/test_deferredtask.py
  tests/core/test_scripts.py
Labels: DB migration, feature

#1746 Update how we handle axis availability information 401 response (PP-1081)
  api/axis.py
  tests/api/files/axis/availability_invalid_token.xml
  tests/api/files/axis/availability_patron_not_found.xml
  tests/api/test_axis.py
Labels: bug
