Repository ThePalaceProject/circulation, pull requests merged in 2025-04, with the labels that each got.

#2401 Alphabetize items in admin UI (PP-2351)
  alembic/versions/20250409_b96d67e65177_sort_library_languages.py
  src/palace/manager/api/admin/controller/integration_settings.py
  src/palace/manager/integration/configuration/library.py
  tests/manager/api/test_config.py
  tests/manager/integration/configuration/test_library.py
  tests/migration/conftest.py
  tests/migration/test_20250409_b96d67e65177_sort_library_languages.py
Labels: DB migration, feature

#2404 Holds report includes only books with holds. (PP-2317)
  src/palace/manager/celery/tasks/generate_inventory_and_hold_reports.py
  tests/manager/celery/tasks/test_generate_inventory_and_hold_reports.py
Labels: bug

#2405 Alphabetize lists and lanes (PP-2351)
  src/palace/manager/api/admin/controller/custom_lists.py
  src/palace/manager/sqlalchemy/model/customlist.py
  tests/manager/api/admin/controller/test_custom_lists.py
Labels: feature

#2410 Bump pillow from 11.2.0 to 11.2.1
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#2433 Handle case of hold on unsupported Overdrive content (PP-2415)
  src/palace/manager/api/circulation.py
  src/palace/manager/api/overdrive/api.py
  src/palace/manager/service/analytics/analytics.py
  src/palace/manager/service/analytics/eventdata.py
  src/palace/manager/service/container.py
  src/palace/manager/sqlalchemy/model/patron.py
  tests/manager/api/overdrive/test_api.py
  tests/manager/sqlalchemy/model/test_patron.py
Labels: bug
