Repository ThePalaceProject/circulation, pull requests merged in 2025-06, with the labels that each got.

#2532 CORS headers for patron auth token responses. (PP-2651)
  src/palace/manager/api/routes.py
Labels: bug

#2540 Implement B&T DRM (PP-2133)
  poetry.lock
  pyproject.toml
  src/palace/manager/api/axis/api.py
  src/palace/manager/api/axis/constants.py
  src/palace/manager/api/axis/exception.py
  src/palace/manager/api/axis/manifest.py
  src/palace/manager/api/axis/models/json.py
  src/palace/manager/api/axis/parser.py
  src/palace/manager/api/axis/requests.py
  src/palace/manager/api/axis/settings.py
  src/palace/manager/api/bibliotheca.py
  src/palace/manager/api/circulation.py
  src/palace/manager/api/controller/loan.py
  src/palace/manager/api/enki.py
  src/palace/manager/api/odl/api.py
  src/palace/manager/api/opds_for_distributors.py
  src/palace/manager/api/overdrive/api.py
  src/palace/manager/core/opds2_import.py
  src/palace/manager/core/opds_import.py
  src/palace/manager/feed/annotator/circulation.py
  src/palace/manager/feed/serializer/opds.py
  src/palace/manager/feed/serializer/opds2.py
  src/palace/manager/feed/types.py
  src/palace/manager/sqlalchemy/model/licensing.py
  src/palace/manager/util/opds_writer.py
  tests/files/axis/availability_with_audiobook_fulfillment.xml
  tests/files/axis/license.json
  tests/files/axis/license_internal_server_error.json
  tests/files/axis/license_invalid_isbn.json
  tests/fixtures/database.py
  tests/manager/api/axis/models/test_json.py
  tests/manager/api/axis/test_api.py
  tests/manager/api/axis/test_exception.py
  tests/manager/api/axis/test_manifest.py
  tests/manager/api/axis/test_parser.py
  tests/manager/api/axis/test_requests.py
  tests/manager/api/axis/test_settings.py
  tests/manager/api/controller/test_loan.py
  tests/manager/feed/test_library_annotator.py
  tests/manager/feed/test_opds2_serializer.py
  tests/manager/feed/test_opds_serializer.py
  tests/mocks/circulation.py
Labels: cleanup migration, feature

#2543 Cleanup migration Axis 360 settings (PP-2133)
  alembic/versions/20250623_87051f7b2905_update_axis_settings.py
  src/palace/manager/api/axis/settings.py
  tests/manager/api/axis/test_settings.py
  tests/migration/conftest.py
  tests/migration/test_20250623_87051f7b2905_update_axis_settings.py
Labels: DB migration

#2549 [PP-2639] Add a new report to the inventory and holds reports zip tha…
  src/palace/manager/celery/tasks/generate_inventory_and_hold_reports.py
  tests/manager/celery/tasks/test_generate_inventory_and_hold_reports.py
Labels: feature
