Repository ThePalaceProject/circulation, pull requests merged in 2025-07, with the labels that each got.

#2575 Make sure classifier lookup isn't dependent on import order (PP-2682)
  src/palace/manager/core/classifier/__init__.py
  src/palace/manager/core/classifier/age.py
  src/palace/manager/core/classifier/bic.py
  src/palace/manager/core/classifier/bisac.py
  src/palace/manager/core/classifier/ddc.py
  src/palace/manager/core/classifier/gutenberg.py
  src/palace/manager/core/classifier/keyword.py
  src/palace/manager/core/classifier/lcc.py
  src/palace/manager/core/classifier/overdrive.py
  src/palace/manager/core/classifier/simplified.py
  src/palace/manager/sqlalchemy/model/classification.py
  tests/manager/core/classifiers/test_classifier.py
  tests/manager/core/classifiers/test_overdrive.py
  tests/manager/core/test_opds_import.py
Labels: bug

#2607 Add setting to prioritize Boundless DRM (PP-2744)
  src/palace/manager/api/boundless/api.py
  src/palace/manager/api/boundless/settings.py
  src/palace/manager/api/odl/api.py
  src/palace/manager/api/opds_for_distributors.py
  tests/manager/api/boundless/test_api.py
Labels: feature

#2617 Fix size update for large custom lists. (PP-2711)
  src/palace/manager/core/query/customlist.py
  src/palace/manager/sqlalchemy/model/customlist.py
Labels: bug

#2633 Add created_at and updated_at timestamps to Editions table (PP-2722)
  alembic/versions/20250721_1290ca457ee4_add_created_and_updated_timestamps_to_.py
  src/palace/manager/data_layer/bibliographic.py
  src/palace/manager/sqlalchemy/model/edition.py
  tests/manager/data_layer/test_bibliographic.py
  tests/manager/sqlalchemy/model/test_edition.py
Labels: DB migration, feature

#2628 [PP-2713] Fulfillment of open access books in OPDS for Distributors
  src/palace/manager/integration/license/opds/opds_for_distributors.py
  tests/manager/integration/license/opds/test_opds_for_distributors.py
Labels: bug
