Repository ThePalaceProject/circulation, pull requests merged in 2025-10, with the labels that each got.

#2773 Add SAML template parameter support for OPDS2 token authentication (PP-2990)
  src/palace/manager/integration/license/opds/opds2/api.py
  tests/manager/integration/license/opds/opds2/test_api.py
Labels: feature

#2774 Handle unknown collection protocols gracefully
  src/palace/manager/api/circulation_manager.py
  src/palace/manager/celery/tasks/patron_activity.py
  src/palace/manager/sqlalchemy/model/collection.py
  tests/manager/api/test_controller_cm.py
  tests/manager/celery/tasks/test_patron_activity.py
  tests/manager/sqlalchemy/model/test_collection.py
Labels: bug

#2775 Remove Enki integration support 🔥
  bin/enki_import
  bin/enki_reaper
  docker/ci/test_scripts.sh
  docker/services/cron/cron.d/circulation
  src/palace/manager/integration/license/enki.py
  src/palace/manager/service/integration_registry/license_providers.py
  src/palace/manager/sqlalchemy/constants.py
  src/palace/manager/sqlalchemy/model/collection.py
  src/palace/manager/sqlalchemy/model/datasource.py
  tests/files/enki/checked_out_acs.json
  tests/files/enki/checked_out_direct.json
  tests/files/enki/checkout_success.json
  tests/files/enki/get_item_french_title.json
  tests/files/enki/get_recent_activity.json
  tests/files/enki/get_update_titles.json
  tests/files/enki/item_metadata_single.json
  tests/files/enki/login_unsuccessful.json
  tests/files/enki/no_copies.json
  tests/files/enki/patron_response.json
  tests/files/enki/pdf_document_entry.json
  tests/manager/integration/license/test_enki.py
  tests/mocks/enki.py
Labels: incompatible changes

#2781 Fix race condition in IntegrationConfiguration.context_update (PP-2787)
  src/palace/manager/sqlalchemy/model/integration.py
  tests/manager/sqlalchemy/model/test_integration.py
Labels: bug

#2789 Correctly log SAML patron id extraction failure (PP-3020)
  src/palace/manager/integration/patron_auth/saml/controller.py
  src/palace/manager/integration/patron_auth/saml/metadata/model.py
  src/palace/manager/integration/patron_auth/saml/provider.py
  tests/manager/integration/patron_auth/saml/metadata/test_model.py
  tests/manager/integration/patron_auth/saml/test_controller.py
  tests/manager/integration/patron_auth/saml/test_provider.py
Labels: bug

#2791 Update project dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#2786 Add configurable reaping schedules for OPDS2 collections (PP-2787)
  poetry.lock
  pyproject.toml
  src/palace/manager/celery/tasks/opds2.py
  src/palace/manager/integration/license/opds/opds2/api.py
  src/palace/manager/integration/license/opds/opds2/settings.py
  tests/fixtures/database.py
  tests/manager/celery/tasks/test_opds2.py
  tests/manager/integration/license/opds/opds2/test_api.py
  tests/manager/integration/license/opds/opds2/test_settings.py
Labels: feature
